### ISSUE TITLE
Error: Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by LiamAttardcol** [dansomething/coc-groovy#29]
coc-groovy is not starting and I'm getting the following error when opening the CocOpenLog

```
2022-05-03T20:44:09.750 ERROR (pid:12996) [extensions] - Error on createExtension coc-groovy from /home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js Error: Cannot find module 'node:fs'
Require stack:
- /home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js
- /home/lMYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at i (/home/MYNAME/.vim/plugged/coc.nvim/build/index.js:226:42120)
    at Object.e.exports (/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js:1:123381)
    at n (/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js:1:156664)
    at Module.<anonymous> (/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js:1:123209)
    at n (/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js:1:156664)
    at Object.<anonymous> (/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js:1:108623)
    at n (/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js:1:156664) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js',
    '/home/MYNAME/.config/coc/extensions/node_modules/coc-groovy/lib/index.js'
  ]
}
```

**Comment by LiamAttardcol** [comment]
Solved the issue by updating node js from version 12.20 (recommended version of coc readme) to node 16

**Comment by dansomething** [comment]
Node 14.x should work too. I could look at supporting Node 12.x, but it is quite old now.
